export enum CART_ACTIONS {
    UPDATE_SIZE = "UPDATE_SIZE",
    UPDATE_SIZE_SUCCESS = "UPDATE_SIZE_SUCCESS",
    UPDATE_COLOR = "UPDATE_COLOR",
    UPDATE_COLOR_SUCCESS = "UPDATE_COLOR_SUCCESS",
    UPDATE_FAVOURITE = "UPDATE_FAVOURITE",
    UPDATE_FAVOURITE_SUCCESS = "UPDATE_FAVOURITE_SUCCESS"
}
